import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: "#00162F",
    },
    scrollContent: {
        flexGrow: 1,
        alignItems: "center",
        paddingVertical: 20,
    },
    cardContainer: {
        alignItems: "center",
        maxWidth: 650, 
        alignSelf: "center",
    },
    svgContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
    },
    logo: {
        width: "100%",
        height: 120,
        alignSelf: "center",
        resizeMode: "contain",
        marginVertical: 10,
    },
    subtitleText: {
        color: "white",
        fontSize: 16,
        marginBottom: 20,
        textAlign: 'center',
    },
    primaryButton: {
        backgroundColor: "#003673",
        paddingVertical: 14,
        borderRadius: 30,
        alignItems: "center",
        width: '100%',
        height: "100%",
        maxHeight: 205,
        maxWidth: 620,
        marginVertical: 8,
        elevation: 3,
    },
    secondaryButton: {
        backgroundColor: "#000000",
        paddingVertical: 14,
        borderRadius: 30,
        alignItems: "center",
        width: '100%',
        height: "100%",
        maxHeight: 205,
        maxWidth: 620,
        marginVertical: 8,
        elevation: 3,
    },
    buttonText: {
        color: "white",
        fontSize: 18,
        fontWeight: "bold",
    },
    dividerText: {
        color: "white",
        fontSize: 14,
        marginVertical: 20,
        textAlign: 'center',
    },
    socialContainer: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: 'center',
        gap: "40%", 
        width: '100%',
        marginTop: "20%",
    },
    socialButton: {
        backgroundColor: "#ffffff",
        borderRadius: 35,
        height: 60,
        width: 60,
        justifyContent: "center",
        alignItems: "center",
        elevation: 3,
    },
    logoM: {
        width: 28,
        height: 28,
        resizeMode: "contain",
    },
    logoG: {
        width: 28,
        height: 28,
        resizeMode: "contain",
    },
});